### ISSUE TITLE
segfaults on qubes

### ISSUE THREAD

**Issue by 0xYUANTI** [digitalbitbox/bitbox-wallet-app#1430] opened 2021-09-02 14:44 UTC
Hi,
on latest qubes, after installing from rpm, BitBox just core dumps with a segfault after printing "Use of deprecated not thread-safe setter, use setUrlRequestInterceptor instead". 

might want to look into that since presumably a lot of crypto ppl use qubes?

**Comment by x1ddos** [comment] 2021-09-02 17:01
Hey @0xYUANTI. Which Qubes version are you running? I'll install and try to reproduce.

**Comment by 0xYUANTI** [comment] 2021-09-03 07:06
4.0.4 on certified hardware

**Comment by benma** [comment] 2021-09-06 08:41
@0xYUANTI 

Could you please try launching the v4.28.2 AppImage and seeing if that segfaults too?

https://github.com/digitalbitbox/bitbox-wallet-app/releases/tag/v4.28.2

We enabled hardware accelerated rendering in v4.29.0 which is a potential source of the problem. If the previous version runs there is a high chance this was the cause, otherwise we have to keep looking.

**Comment by thisconnect** [comment] 2021-09-14 14:03
I hardware accelerated rendering was the issue v4.29.1 should fix it as it is disabled.

> We enabled hardware accelerated rendering in v4.29.0 which is a potential source of the problem. If the previous version runs there is a high chance this was the cause, otherwise we have to keep looking.

**Comment by benma** [comment] 2021-11-22 15:18
@0xYUANTI could you upgrade to BitBoxApp v4.30.0 (https://shiftcrypto.ch/download/) and let us know if you still have the same problem?

**Comment by benma** [comment] 2023-01-30 08:58
Closing this as it seems to work well now - tested on QubesOS 4.1.1.

**Closed by benma** 2023-01-30 08:58 UTC
Labels: more-info-required
