### ISSUE TITLE
BTC Replace-by-Fee (RBF) in the Bitbox application

### ISSUE THREAD

**Issue by Krabtus** [digitalbitbox/bitbox-wallet-app#2679] opened 2024-04-21 05:03 UTC
Is it correct that the Bitbox Desktop application does not offer a Replace-by-Fee (RBF) function? Or have I overlooked something?

This feature would be highly desirable, as Replace-by-Fee (RBF) is an important function in the realm of transaction flexibility. RBF allows users to adjust the fees of their transactions retrospectively if they are not confirmed quickly enough due to network congestion. This is particularly useful in urgent transaction scenarios or when network fee conditions change rapidly. By implementing RBF into the Bitbox Desktop application, users would gain improved control over their transactions and be better able to adapt to unforeseen network conditions.

Is work already being done in this direction?

**Comment by benma** [comment] 2024-04-21 09:04
It is correct that the BitBoxApp does not currently have this feature. The transactions made by the BitBoxApp are marked as replaceable though, which means you can replace them with other wallets that connect to the BitBox02, such as Sparrow or Electrum. 

We'd definitely like to add this feature as some point. 

Closing this a a duplicate of https://github.com/digitalbitbox/bitbox-wallet-app/issues/1206.

**Closed by benma** 2024-04-21 09:04 UTC
Labels: duplicate, feature
